### ISSUE TITLE
As a user, I want the Table CraigslistLocation and CityStreetSpot has the primary key - c_id so that the user won't let the app crash when they are trying to key in the already existed c_id.

### ISSUE THREAD

**Issue by KShih** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#140]
**User story**
As a user, I want the Table CraigslistLocation and CityStreetSpot has the primary key - c_id so that the user won't let the app crash when they are trying to key in the already existed c_id.

**Acceptance criteria**

**Definition of Done**
I know this is done when I try to enter the existed c_id, and the table will block us to do so.

**Comment by ab7289** [comment]
verified in develop
