### ISSUE TITLE
As a renter, I want to be able to set a filter for number of bedrooms so that I get only the listings that have the desired number of bedrooms.

### ISSUE THREAD

**Issue by mok232** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#23]
**User story**
As a renter, I want to be able to set a filter for number of bedrooms so that I get only the listings that have the desired number of bedrooms.

**Acceptance criteria**
Apartments are filtered correctly according to the number of bedrooms.

**Definition of Done**
The renter can filter apartments based on the desired number of bedrooms.

**Comment by ab7289** [comment]
tested in master
