### ISSUE TITLE
As a renter, I want to be able to set a price range so that I only review listings that are within my budget.

### ISSUE THREAD

**Issue by mok232** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#24]
**User story**
As a renter, I want to be able to set a price range so that I only review listings that are within my budget.

**Acceptance criteria**
Apartments are filtered correctly according to the price range.

**Definition of Done**
The renter can filter apartments based on the desired price range.

**Comment by ab7289** [comment]
tested in master
