### ISSUE TITLE
As landlord, I want to be able to edit a location's information so that I can insure that the data displayed to other users reflects what is currently the case.

### ISSUE THREAD

**Issue by ab7289** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#26]
**User story**

As landlord, I want to be able to edit a location's information so that I can insure that the data displayed to other users reflects what is currently the case.

**Acceptance criteria**

The updated data is persisted and can be viewed by other users.

**Definition of Done**

I will know this is done when a landlord user can can click an 'Edit' button on a location that they own, modify some part of that location's information, save, and then other users can view the updated information.

**Comment by alldne** [comment]
(Sorry accidentally moved it to the icebox. Moved it to the New Issues)

**Comment by ab7289** [comment]
tested in master
