### ISSUE TITLE
Testing day bug - pagination div for search results

### ISSUE THREAD

**Issue by abe-shek** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#267]
# Summary
Pagination in the search results page returns a long list of pages which breaks the UIUX
 
# More information
## Steps to Reproduce
- Search for a rather general query say, Brooklyn 

## Expected Results
The pagination div should present only a select few (important) page numbers something like - current, current +- 3, prev, next  

## Actual Results
The pagination div becomes horizontally scrollable listing all the page numbers

# Environments
## Browser
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

## OS
Windows 10

**Comment by ab7289** [comment]
closed in #265
