### ISSUE TITLE
"list index out of range" error on apartment upload page

### ISSUE THREAD

**Issue by vmoros** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#268]
# Summary
If you give an address which Google Maps can't find, the "g_data" list will be empty, [because of line 14 in external/googleapi/fetch.py](https://github.com/gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries/blob/develop/external/googleapi/fetch.py#L14).

The problem is that [line 221 of location/views.py says `g_data[0]`](https://github.com/gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries/blob/develop/location/views.py#L221) so that's a list index out of range, if the list is empty.

# More information
## Steps to Reproduce
* Go to the apartment upload page
* Enter this info:
    * City: Test
    * State: AK
    * Address: 123 Test Ave
    * Zip Code: 99999
    * Rent Price: 1
    * Bedrooms: 1
    * Image: any image file
    * Suite Number: 1
    * Description: Test
* Click "Upload!" and see a "list index out of range" error
![image](https://user-images.githubusercontent.com/13837978/69653902-e76fbd80-1041-11ea-9ede-f55d16e20e9a.png)

## Expected Results
The page should say "Address not found" instead of crashing

## Actual Results
"list index out of range" error

# Environments
## Browser
Chrome 78.0.3904.108

## OS
Windows 10

**Comment by ab7289** [comment]
closed in #321
