### ISSUE TITLE
"integer out of range" error on apartment upload page

### ISSUE THREAD

**Issue by vmoros** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#269]
# Summary
If you give a huge number in any of the numeric fields of the apartment upload page (Rent Price, Bedrooms, Suite Number), you'll get an "integer out of range" error.

# More information
## Steps to Reproduce
* Go to the apartment upload page
* Enter this info:
    * City: New York
    * State: NY
    * Address: 1 Test St
    * Zip Code: 11217
    * Rent Price: 1
    * Bedrooms: 999999999999999999
    * Image: any image file
    * Suite Number: 1
    * Description: Test
* Click "Upload!" and see an "integer out of range" error
![image](https://user-images.githubusercontent.com/13837978/69654616-176b9080-1043-11ea-8533-590331491292.png)

## Expected Results
The page should say "please give me a smaller number" instead of crashing

## Actual Results
"integer out of range" error

# Environments
## Browser
Chrome 78.0.3904.108

## OS
Windows 10

**Comment by ab7289** [comment]
closed in #321
