### ISSUE TITLE
Some search queries result in a search outside of NYC

### ISSUE THREAD

**Issue by vmoros** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#270]
# Summary
The search page seems to try to turn the user's search query into a location, and then it searches near that location. The problem is that sometimes that location is outside of NYC.

# More information
## Steps to Reproduce
- Go to the home page and search for "Broadway"
- See that the page is searching for 720 South Kenosha Avenue, Tulsa, OK, 74120, which is probably not what the user wanted
![image](https://user-images.githubusercontent.com/13837978/69657804-0160ce80-1049-11ea-8fde-7204c0aa742c.png)
- Search for "10th St" and see that the page is searching for 10th Street East, Saint Paul, MN, 55101
![image](https://user-images.githubusercontent.com/13837978/69658085-85b35180-1049-11ea-8c48-5356e12ab9d5.png)

## Expected Results
If I search for "Broadway", I should see apartments that are on Broadway, such as this one
![image](https://user-images.githubusercontent.com/13837978/69658252-d4f98200-1049-11ea-9a5c-3293f6b38221.png)

## Actual Results
When I search for "Broadway", I get no results

# Environments
## Browser
Chrome 78.0.3904.108

## OS
Windows 10

**Comment by ab7289** [comment]
closed in #311
