### ISSUE TITLE
Map doesn't load when there are hundreds of search results

### ISSUE THREAD

**Issue by vmoros** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#271]
# Summary
If you search something that gives lots of search results, like "New York", and then you click "See Apartments on Map", the map won't load.

# More information
## Steps to Reproduce
- Go to the home page and search "New York"
- See that you get dozens of pages of results (I got 73 pages)
- Click "See Apartments on Map", wait 10 minutes, see that the map still hasn't loaded
![image](https://user-images.githubusercontent.com/13837978/69658897-1a6a7f00-104b-11ea-99aa-2de7afd573f7.png)

## Expected Results
The map should load or the page should say "We can't show you the map because there are too many apartments"

## Actual Results
The map doesn't load

# Environments
## Browser
Chrome 78.0.3904.108

## OS
Windows 10

**Comment by ab7289** [comment]
closed in #321
