### ISSUE TITLE
Looking for rental apartment brings results that are hard to understand

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#272]
# Summary
Cant understand the search results

# More information
## Steps to Reproduce
Start at home page
Search for 11214 zip code
Limit search to 2 bedrooms using handy search on the top of the page. This results in the following URL http://master-branch.herokuapp.com/search/?query=11214&min_price=&max_price=&bed_num=1&search=Go
Click on Go
I see 2 apartments, I select "8748 Bay 16th Street, Brooklyn, NY, 11214"
The next page shows Apartments with rental price of 17499. When I click on that I see the next page with the following , no picture available and the description says 
"8748 Bay 16th Street, Brooklyn, NY, 11214
Bedrooms: 2
$17499.00
(Default Description) Bright one bedroom apartment in the heart of Bay Ridge. Located in the 80's near 3rd Avenue the property is steps to shopping and restaurants and a short walk to the R train 86th Street station. The apartment is in a walk-up building. It features an eat-in kitchen, hardwood floors and freshly painted rooms. Good credit and proof of income are needed."

## Actual Results
It says 2 bedrooms and then it says one bedroom in the description
The rent seems to be a bit high?

Most importantly - it is not clear what to do next. How do I actually rent this apartment?
Where is the "Rent" button?

## Note
This user experience is unsatisfying. Not clear what the user would do next 

# Environments

## Browser
Google Chrome

## OS
Linux

**Comment by ab7289** [comment]
closed in #313
