### ISSUE TITLE
Most rental apartments appear to have the same generic description

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#273]
# Summary
I don't see the actual data on the rental apartments

# More information
## Steps to Reproduce
Search for rentals in 11214 zip code.
Most of the apartments have no pictures and the same description.
Example, http://master-branch.herokuapp.com/location/578/apartment/1008
 
## Expected Results
I should be able to see the actual data

## Actual Results
Most of the apartments have no pictures and the same description.
Example, http://master-branch.herokuapp.com/location/578/apartment/1008

## Note
Is the site not reading the actual data yet?

**Comment by ab7289** [comment]
closed in #315
