### ISSUE TITLE
Managing large number of results

### ISSUE THREAD

**Issue by ahanif19** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#274]
# Summary
On the landing page, I searched for "Brooklyn". This returned quite a few results and the web page keeps extending to the right with all of the page numbers and no other content. 

It might be easier to use "previous" and next" or "first" and "last" buttons rather than enumerating all of the pages

# More information
## Steps to Reproduce
- Login in as a tenant
- Search for Brooklyn 
- On the results page, scroll to the right

## Expected Results
I shouldn't see a list of all the page numbers with white space above it

## Actual Results
I see a small subset of the listings and all of the pages that have a relevant listing

## Screenshot:

![image](https://user-images.githubusercontent.com/54873399/69663017-66b9bd00-1053-11ea-9d1c-aeb573569544.png)

## Note
It happens occasionally

# Environments
## Browser
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

## OS
macOS Catalina

**Comment by de846** [comment]
I have this issue too.

**Comment by ab7289** [comment]
closed in https://github.com/gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries/pull/265
