### ISSUE TITLE
Basic UI fixes & form validations needed

### ISSUE THREAD

**Issue by varshasivakumar** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#276]
# Summary
The entire app seemed to be good and couldn't really find major bugs as such. This issue is based on few UI fixes that'll make the User Experience better.

1. Form field validations can be made stronger. It let me enter digits for First Name & negative values for suite number.

<img width="313" alt="first_name_validation" src="https://user-images.githubusercontent.com/45160387/69668095-3840df80-105d-11ea-80e4-91ff86326db3.PNG">
<img width="420" alt="upload apartment checks" src="https://user-images.githubusercontent.com/45160387/69668104-3f67ed80-105d-11ea-98da-a0e9409b5dfc.PNG">

2. Pagination needs to be fixed. As of right now I need to use the scroll bar to view the last page.

<img width="960" alt="pagination_fix" src="https://user-images.githubusercontent.com/45160387/69668233-7938f400-105d-11ea-8b4f-7a1dc8199845.PNG">

3. Basic UI fix : Not sure why it showed a broken UI for the first two times I tried logging in (I'm guessing this was your old UI)

<img width="960" alt="oldUI" src="https://user-images.githubusercontent.com/45160387/69668339-ae454680-105d-11ea-8cc9-c702977ddf96.PNG">

<img width="634" alt="UI fixes" src="https://user-images.githubusercontent.com/45160387/69668359-ba310880-105d-11ea-89fc-142d12c49c1f.PNG">

**Comment by ab7289** [comment]
closed in #321
