### ISSUE TITLE
Apartment I added does not show in search

### ISSUE THREAD

**Issue by ppietraszko** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#277]
# Summary
I uploaded my own apartment and then I tried to search for it via zip code, min price, max price and bedroom and did not get any results. 

# More information
## Steps to Reproduce
- First I added an apartment with a zip code of 11385 and the city name to be Ridgewood
- Searched for the apartment by entering a zip code of 11385 and the correct number of bedrooms and price range
- Then I got a result that there were no locations

## Expected Results
I should be able to see an apartment that was added by a user. 

## Actual Results
Apartment that was added did not show in search. See below images. 
1) Apartment is shown as added: 
<img width="1440" alt="Screen Shot 2019-11-26 at 4 13 20 PM" src="https://user-images.githubusercontent.com/54864011/69673472-6546bf80-1068-11ea-8abc-6c6a27a024d2.png">

2) Apartment is not available in search: 
<img width="1440" alt="Screen Shot 2019-11-26 at 4 13 12 PM" src="https://user-images.githubusercontent.com/54864011/69673558-8b6c5f80-1068-11ea-82ba-dd5940242c92.png">

## Note
Tested search on different users and still does not show. 
It looks like when entering a zip code of 11385 in the search it defaults to Queens, NY, 11385 even though Ridgewood, NY is still a part of 11385. Look into changing the search to be strictly by zip code.

# Environments
## Browser
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

## OS
macOS Mojave Version 10.14.6

**Comment by ab7289** [comment]
closed in #311
