### ISSUE TITLE
Random results when location is outside NY

### ISSUE THREAD

**Issue by bhas2797** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#279]
# Summary
I searched for "Australia" , and got results for apartments in Queens.
Further, i got results for "california" too.

# More information

## Expected Results
There should be an error message which says my search is not valid

## Actual Results
![Screenshot 2019-11-26 at 5 29 12 PM](https://user-images.githubusercontent.com/54854035/69678018-59f89180-1072-11ea-9955-aaf99fcb1384.png)

![Screenshot 2019-11-26 at 5 33 27 PM](https://user-images.githubusercontent.com/54854035/69678225-f1f67b00-1072-11ea-82b3-7ea8cb1bdeed.png)

## Note
I could see apartment in california.

# Environments
## Browser
Firefox

## OS
macOS Mojave

**Comment by ab7289** [comment]
closed in #311
