### ISSUE TITLE
Min and max filters in search

### ISSUE THREAD

**Issue by daisycrego** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#280]
# Summary
Something doesn't work

# More information
## Steps to Reproduce
1. Go to advanced search page
2. Enter min = 0, type search, will get no results
3. Enter max = 100000, type search, will get no results

## Expected Results
Setting the min so low or the max so high should return results. 

## Actual Results
Setting the Min and max filters isn't actually returning any apartments.

**Comment by ab7289** [comment]
closed in #321
