### ISSUE TITLE
"See Apartments on Map" feature doesn't display properly for specific streets

### ISSUE THREAD

**Issue by Vedanth15** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#285]
# Summary
The See Apartments on Map feature doesn't display the results even though the address was recorded correctly as per Google. Instead, it showed a piece of maps which isn't rendered properly.
This was encountered when the search was a street in Manhattan - Wall street or Fulton street.
<img width="948" alt="1" src="https://user-images.githubusercontent.com/47909391/69682015-068c4080-107e-11ea-8960-5b7c57fe34f7.PNG">

## Steps to Reproduce
- Go to search and type fulton street or wall street
- click See Apartments on Map

## Expected Results
Should be able to see map and results

## Actual Results
Couldn't see the map

# Environments
## Browser
Mozilla Firefox

## OS
Windows OS

**Comment by ab7289** [comment]
closed in #321
