### ISSUE TITLE
Upload Apartment Confirmation

### ISSUE THREAD

**Issue by mksavic** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#286]
# Summary

What happens after I upload an apartment? It would be nice if the confirmation page gave me a link to it:

<img width="1280" alt="Screen Shot 2019-11-26 at 6 54 06 PM" src="https://user-images.githubusercontent.com/15850452/69682057-363b4880-107e-11ea-9328-97f920eab31a.png">

Right now I don't really know how to find the apartment I just uploaded.

**Comment by ab7289** [comment]
closed in #320
