### ISSUE TITLE
"Search" is not linked to search results

### ISSUE THREAD

**Issue by Vedanth15** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#289]
# Summary
There is a hyperlink for "search" from favorites bar which looks like its a path and would take you to the search page from which you "liked" the apartment. But, on clicking it takes you to fresh search  with "address required" error .
# More information

<img width="607" alt="1" src="https://user-images.githubusercontent.com/47909391/69683572-4275d480-1083-11ea-8d88-b7629b575554.PNG">
<img width="617" alt="2" src="https://user-images.githubusercontent.com/47909391/69683575-473a8880-1083-11ea-9597-2705a3b35b62.PNG">

## Steps to Reproduce
- Go to favorites after logging in
- select an address from your list
- on your top left below the homepage icon or button, you'd find the search/**favaddress 

## Expected Results
I should be able to click search and get the search page from which I "liked" the apartment.

## Actual Results
loads a fresh page with "address required" error 

# Environments
## Browser
Mozilla Firefox

## OS
Windows OS

**Comment by ab7289** [comment]
Closed in https://github.com/gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries/pull/312
