### ISSUE TITLE
Navigation in site from search results. 

### ISSUE THREAD

**Issue by Vedanth15** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#291]
# Summary
There is no direct way of navigating from a current search results page to user's favorites or account or upload apt pages. You have to access search results by pressing back. Or you have to restart search or go through search history in browser (and see location because names are the same) in case you navigated too many pages from your search results page.

## Steps to Reproduce
- search for apartments
- might want to take a look at 1 or 2 of your fav apts and go to your account
- navigate back to search results

## Expected Results
I should be able to click something so i see my search results again right away

## Actual Results
Couldn't find the described feature

# Environments
## Browser
Mozilla firefox

## OS
Windows OS

**Comment by ab7289** [comment]
Closed in https://github.com/gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries/pull/312
