### ISSUE TITLE
Obscure search results

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#292]
# Summary
Some searches return results that are not correct and I cannot understand.

# More information
## Steps to Reproduce
- Search *cs*.
- The result is strange. The address does not even has the letter *c*. And there is not listing.

## Expected Results
It should be something more meaningful.

## Actual Results
Some address that I don't know how is related to the search phrase.

## Note
It happens every time.

# Environments
## Browser
Safari Version 13.0.3 (15608.3.10.1.4)

## OS
macOS Catalina

**Comment by ab7289** [comment]
closed in #311
