### ISSUE TITLE
Create listing with 0 bedroom

### ISSUE THREAD

**Issue by Garima2505** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#293]
# Summary
User can create a listing with 0 bedroom

# More information
## Steps to Reproduce
- When creating listing the bedroom can be selected as 0

## Expected Results
0 bedroom shouldn't be allowed as a listing, 0 can be replaced with studio 
![image](https://user-images.githubusercontent.com/54910935/69686498-f2503f80-108d-11ea-856a-19480c2d59fb.png)

**Comment by ab7289** [comment]
closed in #321
