### ISSUE TITLE
Upload Apartment form has some issues

### ISSUE THREAD

**Issue by utkarshp21** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#294]
## Description
Issues on upload apartment form:

1. City name should be based on the US state selected instead of allowing some random string 
2. Rent price can be set to 0
3. Bedrooms can be set to 0 
4. No image validation, any file can be uploaded 

![nycitystreet](https://user-images.githubusercontent.com/38756289/69689080-f7b18800-1095-11ea-9afd-a9ee15c218e0.gif)

## Expected Behavior

1. City name should be based on the US state selected.
2. Rent price validation 
3. Bedrooms input validation 
4. Image input validation

**Comment by ab7289** [comment]
closed by https://github.com/gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries/issues/304.
