### ISSUE TITLE
Can't see favorite button until I scroll down to the page

### ISSUE THREAD

**Issue by utkarshp21** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#295]
## Description
Can't see favorite button until I scroll down to the page. Adding to favorite is main functionality of the apartment details page, the button should we somewhere visible to user. 

![nycitystreet2](https://user-images.githubusercontent.com/38756289/69690115-c71f1d80-1098-11ea-8802-1ce81d51d6fe.gif)

## Expected Behavior
The add to favorite button should be somehere visible to user without scrolling

**Comment by ab7289** [comment]
closed in #324
