### ISSUE TITLE
Horizontal scroll issue 

### ISSUE THREAD

**Issue by utkarshp21** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#296]
## Description
I can horizontally scroll the page causing the content to go out of the view. 

![nyccitystreet3](https://user-images.githubusercontent.com/38756289/69690744-c6878680-109a-11ea-8645-4520383b3758.gif)

## Expected Behavior
Horizontally scroll should be disabled if there is no content

**Comment by ab7289** [comment]
closed in https://github.com/gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries/pull/265.
