### ISSUE TITLE
I can create non-sensical usernames (@@@@@)

### ISSUE THREAD

**Issue by de846** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#297]
# Summary
I was able to make a username `@@@@@`.

# More information
## Steps to Reproduce
This was accepted by the current username validation

## Expected Results
I think usernames should be more restricted

## Actual Results
I was able to login as a user @@@@@ after making the account.

# Environments
## Browser
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

## OS
macOS Catalina

**Comment by ab7289** [comment]
closed in #321
