### ISSUE TITLE
I can create apartments with non-sensical properties

### ISSUE THREAD

**Issue by de846** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#298]
# Summary
I was able to make an apartment cost more 999 quadrillion dollars
I could also make an apartment with 2147483647 bedrooms.
# More information
## Steps to Reproduce
Create an apartment with bizarre data that tests the boundaries.

## Expected Results
I should be limited to money and bedrooms that exist in the universe.

## Actual Results
I was able to make an apartment that nobody can afford that doesn't exist

![image](https://user-images.githubusercontent.com/16791467/69691186-567a0000-109c-11ea-988e-ade5fe57a818.png)

# Environments
## Browser
Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

## OS
macOS Catalina

**Comment by ab7289** [comment]
closed in #321
