### ISSUE TITLE
Images for apartments not getting displayed

### ISSUE THREAD

**Issue by shaurya133** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#302]
# Summary
Even if I select the most basic filter which is city Manhattan, although I see a lot of listings I cannot see any images of the listing.

## Steps to Reproduce
- log in
- Search Manhattan
- See apartment listings, but without images.

<img width="1279" alt="Screenshot 2019-11-26 at 10 13 30 PM" src="https://user-images.githubusercontent.com/54854259/69692150-241dd200-109f-11ea-8cc6-d176ce5e81f0.png">

**Comment by ab7289** [comment]
closed in #315
