### ISSUE TITLE
As a Renter, I want the favorites page to be styled so the favorited apartments are displayed as cards.

### ISSUE THREAD

**Issue by ab7289** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#329]
**User story**

As a Renter, I want the favorites page to be styled so the favorited apartments are displayed as cards.

**Acceptance criteria**

**Definition of Done**

**Comment by Ayushi-0903** [comment]
Should we have empty favorite button with just outline for the apartments that are not being marked as favorite.
