### ISSUE TITLE
As Renter, I want to update the map view in the Location page.

### ISSUE THREAD

**Issue by ab7289** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#331]
**User story**

As Renter, I want to update the map view in the Location page.

**Acceptance criteria**

**Definition of Done**

I will know this is done when the user clicks on one of the pins in the map view, instead of displaying a link to google maps it displays a miniaturized thumbnail of the apartment picture.

(reach) it would also be cool if the pins displayed the price (similar to zillow).

![Screen Shot 2019-12-05 at 3.44.24 PM.png](https://images.zenhubusercontent.com/5d82ee3ea96ad10001e4917e/3d3a1e57-220a-4ec8-b6ad-5e728b2aeb83)

**Comment by KShih** [comment]
@ab7289 
1. If remove the link to google, the user needs to click into the apartment page to link to the google map. Should we keep them both as we did in the search map view? (but change the link to google_url )
2. I'm not sure if it's necessary to display the price in the pin because there is the price right under the map.

**Comment by ab7289** [comment]
@KShih,  I think having the thumbnail and the price would help visually link the pin to which location it represents in the list.

BTW I think the thumbnail is more important than the price, though both are more "nice to have" than absolutely necessary.

I also the reason why I thought it would be ok to move the google url link to the apartment page is because it seems to me that a user would click on the link when they were interested in really digging into the info about the apartment.  When I would be searching for apartments, I'd only bother to look at it in google (i.e. check it out in street view) when I was already interested in it (i.e. the price and description and other basic info about it looks promising). Others are welcome to weigh in on this.

**Comment by KShih** [comment]
Oh I didn't think about one location has different apartments. I think it is important to have this feature now.
