### ISSUE TITLE
I want user to have different page for same login account

### ISSUE THREAD

**Issue by Ayushi-0903** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#34]
**User story**
An user might play two roles at the same time. For instance the user can a seller and renter. Create different sections under the same account.

**Acceptance criteria**
User should be able to use different sections for different purpose.

**Definition of Done**
User should be able to use different sections for different purpose.

**Comment by ab7289** [comment]
closed in #246 , #247
