### ISSUE TITLE
As a renter, I want to be able to specify the neighborhood so that I can review apartments in the vicinity I am interested in.

### ISSUE THREAD

**Issue by mok232** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#36]
**User story**
As a renter, I want to be able to specify the neighborhood so that I can review apartments in the vicinity I am interested in.

**Acceptance criteria**

**Definition of Done**
I know this is done when I can select a neighborhood of my interest and only see the apartments in that neighborhood.

**Comment by ab7289** [comment]
closed in #319
