### ISSUE TITLE
As a renter, I want to be able to filter apartments based on which floor the apartment is located on so that I can only get apartments on my desired level (e.g. ground floor).

### ISSUE THREAD

**Issue by mok232** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#41]
**User story**
As a renter, I want to be able to filter apartments based on which floor the apartment is located on so that I can only get apartments on my desired level (e.g. ground floor).

**Acceptance criteria**

**Definition of Done**
I know this is done when I only see listings that are on my desired floor level.

**Comment by ab7289** [comment]
The data we have access to does not contain this level of information, so closing this.
