### ISSUE TITLE
As a renter, I want to check reviews for the apartment from the actual previous/current tenant so that I could understand more what it would be like to live there

### ISSUE THREAD

**Issue by alldne** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#45]
**User story**
As a renter, I want to check reviews for the apartment from the actual previous/current tenant so that I could understand more what it would be like to live there

**Acceptance criteria**
The screen where users can check details of the apartment should also include a list of reviews for the apartment

**Definition of Done**
This will be done when a renter sees an apartment on our service, there is a way for a renter to check reviews for it

**Comment by ab7289** [comment]
closed in #174 , #178 , #181 , #188 , #192 .
