### ISSUE TITLE
As a renter/tenant/landlord, I want to have a page that displays relevant information based on if I am a renter/tenant/landlord.

### ISSUE THREAD

**Issue by mok232** [gcivil-nyu-org/fall2019-cs-gy-6063-team-five_fries#77]
**User story**
As a renter/tenant/landlord, I want to have a page that displays relevant information based on if I am a renter/tenant/landlord.

**Acceptance criteria**

**Definition of Done**
I know this is done when

1). The account page for the tenant displays information like link to the apartment he/she is currently staying in, and basic info (name, email, phone number etc.).
2). The account page for the renter displays information like my saved listings (favorites), and basic info (name, email, phone number etc.).
3). The account page for the landlord displays information like all my apartments and if they are rented or not, and basic info (name, email, phone number etc.).

**Comment by ab7289** [comment]
Closed in #226 , #247 , #246
